### ISSUE TITLE
Add xmlns="path/to/schema.xsd"

### ISSUE THREAD

**Issue by HanryuDR** [pdavies011010/atom-xmlvalidate#12]
Can you add 
xmlns="path/to/schema.xsd"
to work instead of needing noNameSpace or whatnot? I'm pretty sure xmlns is a reserved word so it shouldn't break anything when validating.

**Comment by pdavies011010** [comment]
Yes xmlns is a reserved word, but that's not what it's used for. xmlns is used for specifying the namespace for your document.  schemaLocation / noNamespaceSchemaLocation are used for specifying the schema. Since these are standard XML things I'm going to have to say no to this request, unless you can show me documentation that this is how it should behave.
