### ISSUE TITLE
XML Validate Toggle does nothing

### ISSUE THREAD

**Issue by ppazos** [pdavies011010/atom-xmlvalidate#13]
1. installed the package on Atom 1.18.0 / Linux Mint 17.3
2. added the reference to the schema in my XML, tried two ways
  - 1. noNamespaceSchemaLocation="/home/pablo/GitHub/openEHR-OPT/xsd/Version.xsd"
  - 2. xsi:schemaLocation="/home/pablo/GitHub/openEHR-OPT/xsd/Version.xsd"
3. XML Validate Toggle does nothing
4. Right click > XML Validate does nothing

**Comment by ppazos** [comment]
Just saw this alert

atom-xmlvalidate 0.5.0

build@unknown – Cannot find module '/home/pablo/.atom/packages/atom-xmlvalidate/node_modules/libxmljs/build'

How to fix?

**Comment by pdavies011010** [comment]
Sorry for the delay. There are too many issues with building this module due to it's use of a native (C/C++) XML validation library. I am looking at recreating the module using something like https://www.npmjs.com/package/xmllint now, which is pure javascript and won't have the same build dependency issues. I will update when that work is done.
