### ISSUE TITLE
Where can the schemaLocation or noNamespaceSchemaLocation attributes be set?

### ISSUE THREAD

**Issue by caspii** [pdavies011010/atom-xmlvalidate#4]
As a casual Atom user, this is totally unclear to me. Please include this in your README

**Comment by pdavies011010** [comment]
Hi @caspii 
   I will add some notes in the README to make it a little more clear, but this isn't an Atom thing, it's an XML schema thing (in order to validate an XML document, you need a schema to validate against). The schemaLocation and noNamespaceSchemaLocation attributes are generally applied to the top-level element of your XML document. 
   So for example, something like: 

```
<Pets noNamespaceSchemaLocation="http://caspii.com/path/to/schemas/petSchema.xsd">
   <Dog />
   <Cat />
</Pets>
```

or ... 

```
<caspii:Pets xmlns:caspii="http://caspii.com/Caspii" schemaLocation="http://caspii.com/Caspii http://caspii.com/path/to/schemas/petSchema.xsd">
  <Doc />
  <Cat />
</caspii:Pets>
```

  At the moment this plugin only supports using a single XML schema. 
Thanks,
Phill

**Comment by caspii** [comment]
Ok, thanks for the help! 🌻

PS Yes, I am an XML noob

**Comment by pdavies011010** [comment]
No sweat, everybody is a noob sometime! I'll make the documentation more clear.

**Comment by pdavies011010** [comment]
I've updated the README.md with examples of how to set the schema attributes.
